# Generated by Django 5.2.12 on 2026-04-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_blockchain_tx_hash_file_original_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='encryption_key',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
